module.exports = {
  resolver: {
    assetExts: [
      "bmp",
      "gif",
      "jpg",
      "jpeg",
      "png",
      "psd",
      "svg",
      "webp",
      "xml",
      "m4v",
      "mov",
      "mp4",
      "mpeg",
      "mpg",
      "webm",
      "aac",
      "aiff",
      "caf",
      "m4a",
      "mp3",
      "wav",
      "html",
      "pdf",
      "yaml",
      "yml",
      "otf",
      "ttf",
      "zip",
      "heic",
      "avif",
      "db",
    ],
    assetResolutions: ["1", "1.5", "2", "3", "4"],
    platforms: ["ios", "android"],
    sourceExts: ["ts", "tsx", "mjs", "js", "jsx", "json", "cjs", "scss", "sass", "css"],
    blockList: [{}, {}],
    disableHierarchicalLookup: true,
    emptyModulePath:
      "/Users/saki/Documents/Mine/tend/node_modules/.bun/metro-runtime@0.83.3/node_modules/metro-runtime/src/modules/empty-module.js",
    enableGlobalPackages: false,
    extraNodeModules: {},
    nodeModulesPaths: ["node_modules", "/Users/saki/Documents/Mine/tend/node_modules"],
    resolveRequest: null,
    resolverMainFields: ["react-native", "browser", "main"],
    unstable_conditionNames: [],
    unstable_conditionsByPlatform: {
      ios: ["react-native"],
      android: ["react-native"],
      web: ["browser"],
    },
    unstable_enablePackageExports: true,
    useWatchman: true,
    requireCycleIgnorePatterns: [{}],
  },
  serializer: {
    polyfillModuleNames: [],
  },
  server: {
    forwardClientLogs: true,
    port: 8081,
    unstable_serverRoot: ".",
    useGlobalHotkey: true,
    verifyConnections: false,
  },
  symbolicator: {},
  transformer: {
    assetPlugins: [],
    asyncRequireModulePath: "expo/internal/async-require-module",
    assetRegistryPath: "@react-native/assets-registry/registry",
    babelTransformerPath:
      "/Users/saki/Documents/Mine/tend/node_modules/.bun/@expo+metro-config@54.0.16+99484634a90b1f1b/node_modules/@expo/metro-config/build/babel-transformer.js",
    dynamicDepsInPackages: "throwAtRuntime",
    enableBabelRCLookup: true,
    globalPrefix: "",
    hermesParser: false,
    minifierConfig: {
      mangle: {
        toplevel: false,
      },
      output: {
        ascii_only: true,
        quote_style: 3,
        wrap_iife: true,
      },
      sourceMap: {
        includeSources: false,
      },
      toplevel: false,
      compress: {
        reduce_funcs: false,
      },
    },
    minifierPath: "metro-minify-terser",
    optimizationSizeLimit: 153600,
    transformVariants: {
      default: {},
    },
    publicPath: "/assets",
    allowOptionalDependencies: true,
    unstable_allowRequireContext: true,
    unstable_dependencyMapReservedName: null,
    unstable_disableModuleWrapping: false,
    unstable_disableNormalizePseudoGlobals: false,
    unstable_renameRequire: false,
    unstable_compactOutput: false,
    unstable_memoizeInlineRequires: false,
    unstable_workerThreads: false,
    postcssHash: null,
    browserslistHash: null,
    sassVersion: null,
    reanimatedVersion: null,
    workletsVersion: null,
    _expoRelativeProjectRoot: "",
  },
  watcher: {
    additionalExts: ["env", "local", "development"],
    healthCheck: {
      enabled: false,
      filePrefix: ".metro-health-check",
      interval: 30000,
      timeout: 5000,
    },
    unstable_lazySha1: true,
    unstable_workerThreads: false,
    unstable_autoSaveCache: {
      enabled: true,
      debounceMs: 5000,
    },
    watchman: {
      deferStates: ["hg.update"],
    },
  },
  cacheStores: [{}],
  cacheVersion: "1.0",
  projectRoot: ".",
  stickyWorkers: true,
  watchFolders: [
    "/Users/saki/Documents/Mine/tend/node_modules",
    "/Users/saki/Documents/Mine/tend/apps/web",
    "/Users/saki/Documents/Mine/tend/apps/mobile",
    "/Users/saki/Documents/Mine/tend/packages/domain",
    "/Users/saki/Documents/Mine/tend/packages/db",
  ],
  transformerPath:
    "/Users/saki/Documents/Mine/tend/node_modules/.bun/@expo+metro-config@54.0.16+99484634a90b1f1b/node_modules/@expo/metro-config/build/transform-worker/transform-worker.js",
  maxWorkers: 6,
  resetCache: false,
  reporter: {},
};
